// SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
// SPDX-License-Identifier: GPL-3.0-or-later
// Rust guideline compliant 2026-05-18

//! Generates `palette.rs` from the vendored house palette file.
//!
//! `assets/steelbore.toml` is a byte-identical copy of the
//! `steelbore-color-palette` skill asset (Steelbore Standard §11). Every colour
//! value Fairing knows is read from it here, at build time, and never retyped
//! (§11.6). The generated module carries the §11.6.1 registered set, the mono
//! theme, the polarity and counterpart tables and the resolution constants.
//!
//! A malformed palette file is a build failure with a message naming the key,
//! never a silently wrong colour.

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use toml::{Table, Value};

/// The vendored palette file, relative to the crate root.
const ASSET: &str = "assets/steelbore.toml";

/// The eleven §11.1 role tokens: TOML key and generated field name.
const ROLES: [(&str, &str); 11] = [
    ("background", "background"),
    ("surface", "surface"),
    ("surface-alt", "surface_alt"),
    ("foreground", "foreground"),
    ("accent", "accent"),
    ("structure", "structure"),
    ("success", "success"),
    ("error", "error"),
    ("warning", "warning"),
    ("focus", "focus"),
    ("border", "border"),
];

/// The roles the mono theme binds (it has no surface class, §11.1.1).
const MONO_ROLES: [(&str, &str); 9] = [
    ("background", "background"),
    ("foreground", "foreground"),
    ("accent", "accent"),
    ("structure", "structure"),
    ("success", "success"),
    ("error", "error"),
    ("warning", "warning"),
    ("focus", "focus"),
    ("border", "border"),
];

const HIGH_CONTRAST_SUFFIX: &str = "-high-contrast";

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed={ASSET}");
    println!("cargo:rerun-if-changed=build.rs");
    let text = fs::read_to_string(ASSET)?;
    let table: Table = text.parse()?;
    let generated = generate(&table)?;
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").ok_or("OUT_DIR is not set")?);
    fs::write(out_dir.join("palette.rs"), generated)?;
    Ok(())
}

fn generate(table: &Table) -> Result<String, Box<dyn Error>> {
    let meta = section(table, "meta")?;
    let resolution = section(table, "resolution")?;
    let themes = section(table, "themes")?;

    let registered = string_list(meta, "registered-set")?;
    let default_slug = string(meta, "default-theme")?;
    let mono_slug = string(meta, "mono-theme")?;
    if !registered.iter().any(|s| s == default_slug) {
        return Err(format!("default theme `{default_slug}` is not in the registered set").into());
    }
    if !registered.iter().any(|s| s == mono_slug) {
        return Err(format!("mono theme `{mono_slug}` is not in the registered set").into());
    }
    let colour_themes: Vec<&str> = registered
        .iter()
        .map(String::as_str)
        .filter(|s| *s != mono_slug)
        .collect();
    let default_index = colour_themes
        .iter()
        .position(|s| *s == default_slug)
        .ok_or("default theme is the mono theme")?;
    let mono = section(themes, mono_slug)?;
    validate_shape(&colour_themes, mono_slug, mono)?;

    let mut out = String::new();
    writeln!(out, "// Generated by build.rs from {ASSET}; do not edit.")?;
    writeln!(
        out,
        "// Palette file version {} ({}).",
        string(meta, "version")?,
        string(meta, "standard")?
    )?;
    writeln!(out)?;
    let constants = [
        (
            "PALETTE_VERSION",
            "Version of the palette file the themes were generated from.",
            string(meta, "version")?,
        ),
        (
            "PALETTE_STANDARD",
            "The Standard clause the palette file implements.",
            string(meta, "standard")?,
        ),
        (
            "DEFAULT_SLUG",
            "Slug of the family default (§11.4).",
            default_slug,
        ),
        (
            "MONO_SLUG",
            "Slug of the palette-independent mono theme (§11.1.1).",
            mono_slug,
        ),
        (
            "ENV_VAR",
            "Environment variable carrying a theme slug (§11.6.3).",
            string(resolution, "env-var")?,
        ),
        (
            "SYSTEM_FILE",
            "System-wide declaration file (§11.6.4).",
            string(resolution, "system-file")?,
        ),
        (
            "USER_FILE",
            "Per-user declaration file (§11.6.4).",
            string(resolution, "user-file")?,
        ),
    ];
    for (name, doc, value) in constants {
        writeln!(out, "/// {doc}")?;
        writeln!(out, "pub const {name}: &str = {value:?};")?;
    }
    writeln!(out)?;

    writeln!(
        out,
        "/// The §11.6.1 registered colour themes, in palette-file order."
    )?;
    writeln!(out, "pub const REGISTERED: &[Theme] = &[")?;
    for slug in &colour_themes {
        write_theme(&mut out, slug, &colour_themes, table)?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;
    writeln!(
        out,
        "/// The family default theme (§11.4), resolved at compile time."
    )?;
    writeln!(
        out,
        "pub const DEFAULT: &Theme = &REGISTERED[{default_index}];"
    )?;
    writeln!(out)?;

    write_mono(&mut out, mono_slug, mono)?;
    Ok(out)
}

/// Every base palette has its high-contrast sibling and the mono theme has no surface class.
fn validate_shape(
    colour_themes: &[&str],
    mono_slug: &str,
    mono: &Table,
) -> Result<(), Box<dyn Error>> {
    for base in colour_themes
        .iter()
        .filter(|s| !s.ends_with(HIGH_CONTRAST_SUFFIX))
    {
        let sibling = format!("{base}{HIGH_CONTRAST_SUFFIX}");
        if !colour_themes.contains(&sibling.as_str()) {
            return Err(
                format!("base theme `{base}` has no registered `{sibling}` sibling").into(),
            );
        }
    }
    for key in ["surface", "surface-alt"] {
        if mono.contains_key(key) {
            return Err(format!("mono theme `{mono_slug}` must not bind `{key}` (§11.1.1)").into());
        }
    }
    Ok(())
}

/// Emits one `Theme { .. }` literal for `slug`.
///
/// Every role value must be a token of `[palettes.<base>]`: the theme tables
/// are the role contract, the palette tables are the colour inventory, and a
/// value present in one but not the other is a retyped hex (§11.4).
fn write_theme(
    out: &mut String,
    slug: &str,
    colour_themes: &[&str],
    table: &Table,
) -> Result<(), Box<dyn Error>> {
    let resolution = section(table, "resolution")?;
    let theme = section(section(table, "themes")?, slug)?;
    let (base, variant) = match slug.strip_suffix(HIGH_CONTRAST_SUFFIX) {
        Some(base) => (base, "HighContrast"),
        None => (slug, "Base"),
    };
    if !colour_themes.contains(&base) {
        return Err(format!("theme `{slug}` names base `{base}`, which is not registered").into());
    }
    let inventory: Vec<String> = section(section(table, "palettes")?, base)?
        .iter()
        .filter(|(key, _)| key.as_str() != "reference")
        .filter_map(|(_, value)| value.as_str().map(str::to_ascii_uppercase))
        .collect();
    let polarity = match string(section(resolution, "polarity")?, base)? {
        "dark" => "Dark",
        "light" => "Light",
        other => return Err(format!("polarity of `{base}` is `{other}`, not dark/light").into()),
    };
    let counterpart = string(section(resolution, "pair")?, base)?;
    writeln!(out, "    Theme {{")?;
    writeln!(out, "        slug: {slug:?},")?;
    writeln!(out, "        base: {base:?},")?;
    writeln!(out, "        counterpart: {counterpart:?},")?;
    writeln!(out, "        variant: Variant::{variant},")?;
    writeln!(out, "        polarity: Polarity::{polarity},")?;
    writeln!(out, "        roles: Roles {{")?;
    for (key, field) in ROLES {
        let hex = string(theme, key).map_err(|e| format!("theme `{slug}`: {e}"))?;
        if !inventory.contains(&hex.to_ascii_uppercase()) {
            return Err(format!(
                "theme `{slug}` role `{key}` is `{hex}`, not a token of `[palettes.{base}]`"
            )
            .into());
        }
        let (r, g, b) = parse_hex(hex).map_err(|e| format!("theme `{slug}` role `{key}`: {e}"))?;
        writeln!(
            out,
            "            {field}: Rgb::new(0x{r:02X}, 0x{g:02X}, 0x{b:02X}),"
        )?;
    }
    writeln!(out, "        }},")?;
    writeln!(out, "    }},")?;
    Ok(())
}

/// Emits the `MONO` bindings.
fn write_mono(out: &mut String, mono_slug: &str, mono: &Table) -> Result<(), Box<dyn Error>> {
    writeln!(out, "/// The mono theme's ANSI role bindings (§11.1.1).")?;
    writeln!(out, "pub const MONO: MonoRoles = MonoRoles {{")?;
    for (key, field) in MONO_ROLES {
        let name = string(mono, key).map_err(|e| format!("theme `{mono_slug}`: {e}"))?;
        let variant = ansi_variant(name).ok_or_else(|| {
            format!("theme `{mono_slug}` role `{key}`: unknown ANSI slot `{name}`")
        })?;
        writeln!(out, "    {field}: Ansi::{variant},")?;
    }
    writeln!(out, "}};")?;
    Ok(())
}

fn section<'a>(table: &'a Table, key: &str) -> Result<&'a Table, Box<dyn Error>> {
    table
        .get(key)
        .and_then(Value::as_table)
        .ok_or_else(|| format!("missing table `{key}`").into())
}

fn string<'a>(table: &'a Table, key: &str) -> Result<&'a str, Box<dyn Error>> {
    table
        .get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("missing string `{key}`").into())
}

fn string_list(table: &Table, key: &str) -> Result<Vec<String>, Box<dyn Error>> {
    let items = table
        .get(key)
        .and_then(Value::as_array)
        .ok_or_else(|| format!("missing array `{key}`"))?;
    items
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::to_owned)
                .ok_or_else(|| format!("`{key}` holds a non-string entry").into())
        })
        .collect()
}

/// Parses `#RRGGBB` (the only form the palette file uses).
fn parse_hex(hex: &str) -> Result<(u8, u8, u8), Box<dyn Error>> {
    let digits = hex
        .strip_prefix('#')
        .filter(|d| d.len() == 6)
        .ok_or_else(|| format!("`{hex}` is not `#RRGGBB`"))?;
    let channel = |i: usize| u8::from_str_radix(&digits[i..i + 2], 16);
    Ok((channel(0)?, channel(2)?, channel(4)?))
}

/// Maps the palette file's ANSI slot names onto `Ansi` variants.
fn ansi_variant(name: &str) -> Option<&'static str> {
    Some(match name {
        "default" => "Default",
        "black" => "Black",
        "red" => "Red",
        "green" => "Green",
        "yellow" => "Yellow",
        "blue" => "Blue",
        "magenta" => "Magenta",
        "cyan" => "Cyan",
        "white" => "White",
        "bright-black" => "BrightBlack",
        "bright-red" => "BrightRed",
        "bright-green" => "BrightGreen",
        "bright-yellow" => "BrightYellow",
        "bright-blue" => "BrightBlue",
        "bright-magenta" => "BrightMagenta",
        "bright-cyan" => "BrightCyan",
        "bright-white" => "BrightWhite",
        "reverse-video" => "ReverseVideo",
        _ => return None,
    })
}
