// SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
// SPDX-License-Identifier: GPL-3.0-or-later
// Rust guideline compliant 2026-05-18

//! Registered colour themes and their role values.
//!
//! The data lives in `palette.rs`, generated by `build.rs` from the vendored
//! palette file; this module is the typed surface over it.

use std::fmt;

use crate::rgb::Rgb;
use crate::role::Role;

/// Generated from `assets/steelbore.toml`; see `build.rs`.
pub(crate) mod generated {
    use super::{Polarity, Roles, Theme, Variant};
    use crate::ansi::{Ansi, MonoRoles};
    use crate::rgb::Rgb;
    use crate::tokens::{PaletteTokens, Token};

    include!(concat!(env!("OUT_DIR"), "/palette.rs"));
}

/// Which member of a palette's variant pair a theme is (§11.1.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Variant {
    /// The palette as declared.
    Base,
    /// The `-high-contrast` sibling: every foreground lifted to at least 7:1.
    HighContrast,
}

/// The canvas's light/dark class (§11.6.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Polarity {
    /// A dark canvas.
    Dark,
    /// A light canvas (only `steelbore-navywhite` in the family).
    Light,
}

/// The eleven role values of one theme.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Roles {
    /// Canvas.
    pub background: Rgb,
    /// Elevated panels; never text.
    pub surface: Rgb,
    /// Code wells; never text.
    pub surface_alt: Rgb,
    /// Body text.
    pub foreground: Rgb,
    /// Primary accent.
    pub accent: Rgb,
    /// Structure, links, informational text.
    pub structure: Rgb,
    /// Success status.
    pub success: Rgb,
    /// Error status.
    pub error: Rgb,
    /// Warning status.
    pub warning: Rgb,
    /// Focus indicator.
    pub focus: Rgb,
    /// Surface boundaries.
    pub border: Rgb,
}

impl Roles {
    /// The value bound to `role`.
    #[must_use]
    pub const fn get(&self, role: Role) -> Rgb {
        match role {
            Role::Background => self.background,
            Role::Surface => self.surface,
            Role::SurfaceAlt => self.surface_alt,
            Role::Foreground => self.foreground,
            Role::Accent => self.accent,
            Role::Structure => self.structure,
            Role::Success => self.success,
            Role::Error => self.error,
            Role::Warning => self.warning,
            Role::Focus => self.focus,
            Role::Border => self.border,
        }
    }
}

/// One registered colour theme (§11.6.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Theme {
    /// The machine identifier, e.g. `steelbore-high-contrast`.
    pub slug: &'static str,
    /// The slug of the palette this theme belongs to, e.g. `steelbore`.
    pub base: &'static str,
    /// The slug of the palette in the other polarity (§11.6.2).
    pub counterpart: &'static str,
    /// Base or high-contrast sibling.
    pub variant: Variant,
    /// The canvas's polarity.
    pub polarity: Polarity,
    /// The role values.
    pub roles: Roles,
}

impl Theme {
    /// Every registered colour theme, in palette-file order (the mono theme is [`crate::MonoRoles`]).
    #[must_use]
    pub fn registered() -> &'static [Theme] {
        generated::REGISTERED
    }

    /// The family default (§11.4): `steelbore`.
    #[must_use]
    pub fn family_default() -> &'static Theme {
        generated::DEFAULT
    }

    /// The registered colour theme with this slug, if any.
    #[must_use]
    pub fn find(slug: &str) -> Option<&'static Theme> {
        generated::REGISTERED
            .iter()
            .find(|theme| theme.slug == slug)
    }

    /// The colour bound to `role`.
    #[must_use]
    pub const fn color(&self, role: Role) -> Rgb {
        self.roles.get(role)
    }

    /// The palette's base theme (itself for a base theme).
    #[must_use]
    pub fn base_theme(&'static self) -> &'static Theme {
        Self::find(self.base).unwrap_or(self)
    }

    /// The palette's `-high-contrast` sibling, if the palette has one (itself when it is one).
    #[must_use]
    pub fn high_contrast(&'static self) -> Option<&'static Theme> {
        generated::REGISTERED
            .iter()
            .find(|theme| theme.base == self.base && theme.variant == Variant::HighContrast)
    }

    /// The base theme of the counterpart polarity (§11.6.2), if registered.
    #[must_use]
    pub fn counterpart_theme(&self) -> Option<&'static Theme> {
        Self::find(self.counterpart)
    }
}

impl fmt::Display for Theme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.slug)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_is_a_registered_base_theme() {
        let default = Theme::family_default();
        assert_eq!(default.slug, generated::DEFAULT_SLUG);
        assert_eq!(default.variant, Variant::Base);
        assert_eq!(Theme::find(default.slug), Some(default));
        assert_eq!(default.base_theme(), default);
    }

    #[test]
    fn every_high_contrast_theme_has_a_registered_base() {
        for theme in Theme::registered() {
            let base = theme.base_theme();
            assert_eq!(base.variant, Variant::Base, "{theme}");
            assert_eq!(base.polarity, theme.polarity, "{theme}");
            if theme.variant == Variant::HighContrast {
                assert_eq!(base.high_contrast(), Some(theme), "{theme}");
                assert_eq!(theme.high_contrast(), Some(theme), "{theme}");
            }
        }
    }

    #[test]
    fn counterparts_swap_polarity() {
        for theme in Theme::registered() {
            let counterpart = theme
                .counterpart_theme()
                .unwrap_or_else(|| panic!("{theme} has no registered counterpart"));
            assert_ne!(counterpart.polarity, theme.polarity, "{theme}");
        }
    }

    #[test]
    fn roles_get_matches_fields() {
        let theme = Theme::family_default();
        assert_eq!(theme.color(Role::Background), theme.roles.background);
        assert_eq!(theme.color(Role::SurfaceAlt), theme.roles.surface_alt);
        assert_eq!(theme.color(Role::Border), theme.roles.border);
    }

    #[test]
    fn unknown_slug_is_none() {
        assert!(Theme::find("steelbore-mono").is_none());
        assert!(Theme::find("").is_none());
    }
}
