// SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
// SPDX-License-Identifier: GPL-3.0-or-later
// Rust guideline compliant 2026-05-18

//! Deterministic Texinfo rendering of the Needs and Requirements chapters.
//!
//! Each item is an `@anchor` plus `@subheading` (not a node) so the 68
//! requirements stay cross-referenceable without 68 menu entries. Prose is
//! escaped (`@`, `{`, `}`) and a `` `code` `` span becomes `@code{code}`; no
//! other markup is accepted in the TOML, which keeps the generator total.

use std::fmt::Write as _;

use super::model::{Need, Requirement, RequirementSet};

const SPDX_HEADER: &str = "\
@c SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
@c SPDX-License-Identifier: CC-BY-SA-4.0
@c GENERATED by `cargo xtask req-texi` from doc/requirements.toml --- do not edit.
";

/// Escapes Texinfo specials and renders `` `code` `` spans as `@code{}`.
#[must_use]
pub fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 8);
    let mut in_code = false;
    for ch in text.chars() {
        match ch {
            '`' => {
                out.push_str(if in_code { "}" } else { "@code{" });
                in_code = !in_code;
            }
            '@' => out.push_str("@@"),
            '{' => out.push_str("@{"),
            '}' => out.push_str("@}"),
            _ => out.push(ch),
        }
    }
    if in_code {
        out.push('}');
    }
    out
}

/// Renders the `Needs` chapter.
#[must_use]
pub fn render_needs(set: &RequirementSet) -> String {
    let mut out = String::from(SPDX_HEADER);
    out.push_str("\n@node Needs\n@chapter Needs\n\n");
    if !set.meta.needs_preamble.trim().is_empty() {
        out.push_str(&escape(set.meta.needs_preamble.trim()));
        out.push_str("\n\n");
    }
    for need in &set.need {
        render_need(&mut out, need);
    }
    out
}

fn render_need(out: &mut String, need: &Need) {
    let _ = writeln!(out, "@anchor{{{}}}", need.id);
    let _ = writeln!(out, "@subheading {} --- {}", need.id, escape(&need.title));
    let _ = writeln!(out, "@cindex {}", need.id);
    let _ = writeln!(out, "{}", escape(&need.text));
    if !need.who.trim().is_empty() {
        let _ = writeln!(
            out,
            "\n@noindent\nStakeholder: {}.",
            escape(need.who.trim())
        );
    }
    out.push('\n');
}

/// Renders the `Requirements` chapter with one section per group.
#[must_use]
pub fn render_requirements(set: &RequirementSet) -> String {
    let mut out = String::from(SPDX_HEADER);
    out.push_str("\n@node Requirements\n@chapter Requirements\n\n");
    if !set.meta.requirements_preamble.trim().is_empty() {
        out.push_str(&escape(set.meta.requirements_preamble.trim()));
        out.push_str("\n\n");
    }
    out.push_str("@menu\n");
    for group in &set.group {
        let _ = writeln!(out, "* {}::\t{}.", group.node, escape(&group.title));
    }
    out.push_str("@end menu\n\n");

    for group in &set.group {
        let _ = writeln!(
            out,
            "@node {}\n@section {}\n",
            group.node,
            escape(&group.title)
        );
        if !group.intro.trim().is_empty() {
            let _ = writeln!(out, "{}\n", escape(group.intro.trim()));
        }
        for req in set.requirement.iter().filter(|r| r.group == group.id) {
            render_requirement(&mut out, set, req);
        }
    }
    out
}

fn render_requirement(out: &mut String, set: &RequirementSet, req: &Requirement) {
    let _ = writeln!(out, "@anchor{{{}}}", req.id);
    let _ = writeln!(out, "@subheading {} --- {}", req.id, escape(&req.title));
    let _ = writeln!(out, "@cindex {}", req.id);
    out.push_str("@table @asis\n");
    let _ = writeln!(out, "@item Requirement\n{}", escape(&req.text));
    let _ = writeln!(out, "@item Rationale\n{}", escape(&req.rationale));
    if !req.source.is_empty() {
        let rendered: Vec<String> = req
            .source
            .iter()
            .map(|source| {
                if set.need.iter().any(|need| &need.id == source) {
                    format!("@ref{{{source}}}")
                } else {
                    escape(source)
                }
            })
            .collect();
        let _ = writeln!(out, "@item Source\n{}.", rendered.join(", "));
    }
    let _ = writeln!(out, "@item Priority\n{}", req.priority.as_str());
    let _ = writeln!(out, "@item Verification\n{}", req.verification.as_str());
    let _ = writeln!(out, "@item Status\n{}", req.status.as_str());
    let _ = writeln!(out, "@item Milestone\n{}", escape(&req.milestone));
    if let Some(category) = &req.category {
        let _ = writeln!(
            out,
            "@item Assurance\nCategory {} (raised subsystem)",
            escape(category)
        );
    }
    if let Some(notes) = &req.notes {
        let _ = writeln!(out, "@item Notes\n{}", escape(notes));
    }
    out.push_str("@end table\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_specials_and_code_spans() {
        assert_eq!(escape("a@b {c} `--json` d"), "a@@b @{c@} @code{--json} d");
        assert_eq!(escape("`unterminated"), "@code{unterminated}");
    }

    #[test]
    fn rendering_is_deterministic_and_carries_header() {
        let set = RequirementSet {
            meta: super::super::model::Meta {
                project: "P".into(),
                prefix: "FRN".into(),
                standard: "2.12".into(),
                category: "B".into(),
                updated: "2026-10-06".into(),
                needs_preamble: "Why.".into(),
                requirements_preamble: "What.".into(),
            },
            group: vec![],
            need: vec![],
            requirement: vec![],
        };
        let a = render_requirements(&set);
        assert_eq!(a, render_requirements(&set));
        assert!(a.starts_with("@c SPDX-FileCopyrightText"));
        assert!(a.contains("@node Requirements\n@chapter Requirements"));
        assert!(render_needs(&set).contains("@node Needs\n@chapter Needs"));
    }
}
